---
title: "2026年10月"
---
## 10月1日木曜日晴れ
### 午前
ひたすら原稿をする。

1件。何事もなく終える。

職場の後輩が天一へ行きたがる。

無料券配布の日らしい。昼からしんどいものを食べた。

### 午後
営業2件。まあ依頼もらえたいいな。

訪問2件。淡々と終える。

至急の校正1件。喫茶店で済ます。

そのまま土曜日の原稿作業。トホホ...

## 10月2日金曜日晴れ
### 午前
通常通りに寝て起床。

1件訪問。営業2件。

### 午後
3件訪問。

某氏と呑みに行く。

飲み過ぎ。。。

## 10月3日土曜日晴れ
### 午前
研究会。

なんとか乗り切る。

この原稿はもう少しいじって完成させたい。

1件訪問。

### 午後
寝る。

夜中にバーへ。

暇だった。

## 10月4日日曜日雨
### 午前
ゆっくり。

部屋の片付けを少し。

### 午後
ジムへ。それなりに泳ぐ。

週末の原稿を少しだけ進める。

抄録を仕上げるつもりができず。

麦音からのバーへ。流れ流れてたが、まあ日付変わる前には帰宅して寝る。

## 10月5日月曜日雨
### 午前
1件。悩ましいがいつカードを切るかが問題だ。

雨なので抄録の仕上げを進める。

### 午後
3件。

1件は間違い。申し訳ない。

1件は頑張った。

1件はなんとなく関係を築けつつある。

代償手段も使いましょうみたいな流れ。

ジムへ。プール。

夜中少しだけ週末ようの作業するつもりが寝落ち。

## 10月6日火曜日曇りのち晴れ
### 午前
2件。あまりにも何もないので何もいうこともない。

少しだけ抄録をいじる。

悩みに悩んでとりあえず投げる。

多分明日にはこれは終わる。

### 午後
1件。本当に何もないな。トイレ掃除。

日曜日の原稿を書く。

応哲の時から少し変えるつもりだけど、力尽きかけている。

## 10月7日水曜日晴れ
### 午前
3件。特筆すべきことはない。

淡々と回る。2月の抄録は登録を済ませる。

### 午後
3件。
なんとくなく1件は方針を決めつつある。

もう一件も今のところは順調そう。

一件は意地なので何もしようがない。

昼に連絡があり、祖母が亡くなったとのこと。合掌。

私のイメージでは常に穏やかな人であった。

100歳まで生きたので大往生。

自転車を回収するが、お店が閉まっていて修理に出せない。

夜は寝落ち。

## 10月8日木曜日晴れ
### 午前
1件。

### 午後
2件。

<br>
[日記一覧へ戻る](index.qmd)