---
title: "2026年9月"
---

[日記一覧へ戻る](index.qmd)

## 9月10日 木曜日 雨

### 午前

訪問は1件。
残りの時間で要旨を1本書く。

### 午後

3件訪問。平穏に終わる。雨だけが苦痛で仕方ない。

ジムへ行こうとするが会員証を忘れたのでやめる。

喫茶店で代わりに作業。

AIのおかげでパソコンのことに詳しくなりつつある。

## 9月11日 金曜日 曇り時々雨

### 午前

抄録の返信をもらう。

出来たら今日中にいじり倒したいが、どうだろうか。

朝少しだけ。gitについてAIとお勉強。

訪問1件。

### 午後

訪問3件。
バタバタ移動しながら特にトラブルなく終える。

夜某氏と呑みに行く。

久しぶりにしんどい。

## 9月12日 土曜日 晴れ時々曇り

### 午前

寝転がってNetflix。

『ヴィンスステイプルショー』を眺める。

これいい感じだな。

### 午後

寝転がってNetflix

夕方にジム。夜中にバイト。

## 9月13日 日曜日 晴れ時々曇り

### 午前

とりあえず、自転車はスルーアクセルが外せない。

やはりどっかのタイミングで回収してもらうしかない。

パソコンというかgitでひたすらマークダウンファイルをいじる。

### 午後

夕方に出かけることにする。

ジムへ。水泳と筋トレ。

地元のバーで少し語る。

ウェブサイトをひたすらいじる。

少しだけ要旨をいじる。

## 9月14日 月曜日 晴れ時々曇り

### 午前

訪問1件。

課題作りに励む。

### 午後

訪問2件。
1件はひたすら片付けを続ける。

1件はあまりに発話不明瞭のため聞き返すと怒られる。

AIでバックアップ取ってからパソコンのいらんファイルを全て整理させる。

ほぼほぼ終わったのではないか。AIえらい。

呑まずに帰路。

## 9月15日 火曜日 晴れ時々雨
### 午前

メール1件。訪問2件。

気楽に回る。

しかし、1件は維持するのもやっとな感じ。

### 午後

訪問2件。
1件は雨にやられる。

特に何もなく淡々と過ごす。

要旨だけでも完成させるべく弄る。

ほぼ完成。ビールを1杯呑んで帰る。

## 9月16日 水曜日 曇り時々雨
### 午前
CSSとかquartoが何をできるのかひたすら勉強している感じ。

動けない人のための訪問1件。

訪問1件。AIにニュース文の課題ファイルを作るように指示した。

### 午後
失語の人の訪問1件。課題は気に入ってもらう。

問題はきちんと訓練プログラム組めてなかったのではないかという漠然とした不安。

あとは時間を持て余す。窓際属の感じを味わっている。

さらに、サイトをいじり倒す。何をしているのだろうか。

ジムへ行く。水泳と筋トレ。

深夜。schrammeのノートとり。

## 9月17日 木曜日 曇り
### 午前
訪問1件。特に何か準備することがあるわけではない。

空き時間に色々作業。

### 午後
訪問3件。気楽に回る。

論文用のノート取り。

飲みに行く。ダメダメ。3件も回るのはもうできない。

## 9月18日 金曜日 晴れ
### 午前
訪問1件。いつも通り。

ノートを一つ完成させる。

これで11月のやつは少し進んだことになるだろう。

### 午後
訪問3件。淡々と回る。

一人思っているよりも進んでいる。

調べもので上手く使えばいいかなというものあり。

## 9月19日 土曜日 晴れ
### 午前
色々せねばということなんだけどだらだら。

朝はジムへ行く予定で行けた。

### 午後
昼から病院によって精算を済ませる。

ビアバーで少しノートをとる。

某氏と会う。

## 9月20日 日曜日 晴れ
### 午前
朝はジムへ行く予定で行けた。

1件なんだかなとなる件あり。まあ仕方あるまい。

移動。中之島へ。乗る線を間違ってしまってちょっと歩くことに。昨日と同じ。

### 午後
情報概念についてのお勉強。

どの発表も綺麗に話がまとまっていて勉強になった。

発表後の懇親会。二次会まで。楽しく歓談。

## 9月21日 月曜日 曇り
### 午前
とりあえず出かける。

軽く昼食。低カロリー高タンパクを意識して摂取するようにせねば。

### 午後
論文のためのノートとり。

しかし要旨のやつと10月のやつもあるので実はやばい。

ダラダラ呑む。

## 9月22日 火曜日 晴れ
### 午前
ゆっくり起床。

鶏のフリカッセを作る。

まずまずので出来。

明日はパスタと和えるか、チーズでグラタン風にして背徳的な方向か...

### 午後
訪問バイト。2件。

少し慌てるがことなきを得る。

ほぼ同行みたいな感じで嚥下訓練。

少しだけノートをとる。

## 9月23日 水曜日 雨のち晴
### 午前
論文のためのインプットをするつもりが、ローカルのAIを入れるという遊び。

アメリカ版の”The Office”を眺めてしまう。

### 午後