project:
  type: website

website:
  google-analytics: "G-BTBHJJ9F71"
  navbar:
    left: 
      - href: site/index.qmd
        text: "ホーム"
      - href: site/research.qmd
        text: "研究業績"

format:
  html:
    toc: false
    css: styles.css