project:
  type: website

website:
  google-analytics: "G-BTBHJJ9F71"
  navbar:
    collapse: false
    left: 
      - href: site/index.qmd
        text: "home"
      - href: site/research.qmd
        text: "resarch"
      - href: site/posts/diary.qmd
        text: "diary"

format:
  html:
    toc: false
    css: styles.css