---
title: "Bickenbach の健康概念についてのノート"
page-layout: full
date: "2026-09-21" 
lang: ja
draft: true
---

<https://doi.org/10.1007/978-94-024-2252-8_48>

健康関連でもう1本。11月用のインプット。Schrammeが参照していた文献で発表のテーマに使えそうだということで、こちらもノートを残しておく。Bickenbachは、スイス・ルツェルン大学の教授。哲学者・法学者で、専門分野は生命倫理、法哲学、そして障害学らしい。1995年以降、WHOのコンサルタントとして、国際障害分類(ICIDH)を国際生活機能分類(ICF)へと改訂する作業にも関わってたみたい。んでもってSchrammeの文献でも言及されていたもので、気になったから読むことにした。ということでBickenbachの健康概念論文を読んでいこう。

<br>

Bickenbachの論点はWHOの健康概念に関する定義の批判と現在のWHOのアプローチがどのようなものかを紹介する流れになっている。目次は次の通り。

<br>

1. はじめに
2. WHOの健康定義とその哲学的批判
   - 1948年の定義とその哲学的批判
   - 健康についての規範的説明と記述的説明
   - 規範主義への関心の近年の再興
   - WHOの新しいアプローチ
3. 結論

<br>

Bickenbachは歴史的な経緯について触れているので、その整理も最低限敷衍しておきたい。個人的な関心からはWHOの新しいアプローチあたりが大事なんだけど、それだけでは論文の紹介としては甘いので。このノートは結構好き勝手に自由なことを書くつもりだけど、最低限の学術的な正確さは担保したい。あくまで私の中での最低限であって、誰にとってもでもはない。決して。

<br>

WHOの定義についてはCallahan(1973)に代表されるように徹底的に批判されてきた。Callhanの批判の要点は、「健康」を「ウェルビーイング」の語によって定義することは、人間の幸福を医学的アウトカムへ変え、不正義、経済的欠乏、差別のような社会的害悪を、医学的解決を必要とする医学的問題へと変えてしまう、と論じたのである」というフレーズで端的にまとめられている。
しかし、Bickenbachが言うように、このWHOの定義こそ論争を活発化させてきた側面がある。そして、現在の健康概念をめぐる論争がどのような問題に集約されるのかについて、Bickenbachなりのまとめがこの論文の一つの売りになる。

まず、WHO(1948)の特徴は次のようにまとめられる。

<br>

- 健康は問題の不在(高血圧、肥満etc.)だけではなく、何かしらの積極的な側面(たとえば体力がある)を持つ。
- 健康は道具的にも内在的にも価値を持つ。内在的な価値があるため、人々はそれを求める。
- 健康は身体的な側面だけではなく、精神的、社会的側面を有する。

<br>

Callahanらは仮に健康とウェルビーイングを同一視することによる問題を次のように定式化している。たとえば過労死するようなラインで働いている人を考えてみよう。仮にその人が不眠など健康状態を崩すのは、そのような労働時間を強いている社会の問題である。このような過労死の問題を社会問題ではなく、健康という医療の領域に位置づけることは、社会問題の「医療化(medicalize)」ではないかといった批判をしている。つまり、その人が自らメリットデメリットの両方の情報を踏まえて選択しているようなことについても医療の方から規制をかけることが正当化されてしまう可能性が出てくるのである。

<br>

Callahanらは健康概念を説明するためには次の要素を含まないといけないと考えている。

<br>

- 健康概念が直観的には自然的規範(natural norm)であり、かつ倫理的理想(ethical ideal)である。

- 健康は心臓や肺などの機能が統計的に正常範囲の閾値内で保たれているだけではない。

- 健康それ自体は何かしらの理想的な状態であるという直観が人々にある。
<br>

つまり、健康という概念を考えるには、ある種の正常範囲を統計的に定めるという規範的な意味だけでないという点を抑えなければならない。ここを出発点として、哲学者らの疑問が展開される。

<br>
さて、以上のようなWHOの健康概念をめぐる議論を出発点として、哲学者たちは大きく二つの立場に分かれて議論を交わすことになる。

<br>

## Boorseの議論

Boorse(1977)はこの分野の古典になっている。彼の立場はのちに健康についての記述的説明の立場として整理されるものである。彼は、健康についての規範主義と呼ばれる立場を否定することになる。
この目的のために、Boorseは疾病(diease)と病い(illness)の違いを区別する議論を組み立てた。

これに対して規範主義の代表者であるNoldenfeltは次のような議論を組み立てている。







