---
title: 'Princeの「Kiss」の歌詞は価値観の提示かそれともストーリーか？'
author: "UNO Tasuku"
date: "2025-07-04"
lang: ja
toc: false
---

## **目次**

1. 0\. まえがき
2. 1\. 曲の作成経緯
3. 2\. 映画の挿入歌としての「Kiss」
4. 3\. ミュージックビデオとしての「Kiss」
5. 4\. プリンスの曲のジャンル分けについて
6. 5\. 価値観表明としての「Kiss」の歌詞解釈
7. 6\. 物語としての「Kiss」の歌詞解釈
8. 7\. おわりに

### 0. まえがき

　プリンスの「Kiss」がプリンスの代表曲なのはファンの大多数も認めるところでしょう\*1。日本語版のWikiで調べてみるとカバーも多数されていますし、ヒップホップでのサンプリングは言わずもがなです\*2。最近、SNS上でおやっと思う解釈を見ました。自分とは異なる解釈だなと刺激されて、この記事を書いています。ちなみに当該の解釈は、SNS上の短い書き込みだけで、解釈の根拠や解釈の過程が明確に分かりません。なので、良かったらもう少し詳しく解釈の内実を教えて欲しいと考えています。当該ツイートをされた北村先生は著名なシェイクスピア研究者であり、様々な映画への批評等も精力的取り組まれている方で、きっと解釈に明確な根拠があるのだろうと考えています\*3。そのため、その解釈と私の解釈を照らし合わせることで、気づかなかったプリンスの曲の魅力が分かる可能性があるのではないかなと思っており、応答があることを期待しています。さて、個人的におやっとなった解釈は次のようなものです。

[Xの投稿を見る](https://x.com/i/web/status/1932627042719445151)

　なるほど恐らくポップミュージックの歴史の文脈で考えると、授業でプリンスの曲を題材に議論するのもビートルズのようにありになっているのかとか思いつつ、この短いツイートの中になぜそう解釈できるのだろうかと、思わず考え込む箇所が複数ありました。この解釈があったからこそ「Kiss」について自分なりにソースにあたって理解を深めるきっかけになった点にまずは感謝したいです。実際、それくらい引っかかるところがある解釈だった訳です。もう少しはっきり言うなら北村先生はプリンスをそれほど聴いていないというのが予想です。あくまで予想。以下では曲の成立経緯などを簡単にまとめたうえで、自分なりの解釈と上記の解釈になぜ疑問を覚えたのかについてコメントします。以下はこの記事の議論の流れです。まず楽曲がどのような過程で作成されたのかについて確認します。その上で、そもそも「Kiss」は映像・映画・歌詞のいずれの面においても、明確なストーリー性を欠くことを示します。代わりに提案するのは、プリンスが提示するのは一貫した価値観であり、「価値観提示型」の楽曲として読むほうが構造的にも内容的にも整合的であるという見方です。そのために、以下の3つのメディアに沿って検討を進めます。映画『Under the Cherry Moon』における使用文脈を作品の成立経緯などから楽曲単体の文脈での解釈を許容可能かを検討します。さらにミュージックビデオの検討からは楽曲の構造と合致するように作成されており、同時期の他のPVのようにストーリーが見出せないことを示します。最後に歌詞からもそのようなストーリーは見出せず、楽曲がある価値観を提出していると主張します。

### 1. 曲の作成経緯

　そもそもある楽曲を解釈をするためには楽曲の構造分析たとえばコード進行を確認するといった手法や、歌詞を解釈する、他の曲やアーティストとの比較、曲のジャンルやカテゴリー、時代背景等と照らし合わせるなど様々な方法があるでしょう。今回は、そうした作業に移る前に、まずこの曲が作られた経緯やどのようにして世に出たのかについての事実を確認しましょう。事実をしっかりと抑えることは解釈するうえで大きな土台になるからです\*4。そのため、多少冗長になりますが、「Kiss」の成立過程やどのように発表されたかの事実を確認しましょう。そもそもこの曲はプリンスが自身で歌う予定はなかった曲です。実際、プリンスはアコースティックギターでデモを録っており、これをDavid Zに渡しています。

[動画：Prince「Kiss」デモ音源（YouTube）](https://www.youtube.com/watch?v=XXMGp_7vl8w)

　このデモを聴いて、David Zがドラムマシーンを加え、メンバー達とアレンジしたものをマザラティが録音しました。

[動画：Mazarati版「Kiss」（YouTube）](https://www.youtube.com/watch?v=rP_um0428FA)

　このマザラティの録音を聴いてプリンスは気に入り、翌日に！再度自分の曲として「ベースを抜き、かわりにファンキーなギターを入れファルセットでボーカルを入れた」形にアレンジし直し、録音したのです\*5。この時「君たちには良すぎるから、返してもらうよ 'It's too good for you guys. I'm taking it back.'”」とプリンスは言ったそうです。これは、なかなか最低なエピソードですね…　さて、ここまでの曲の作成経緯から分かるように、この曲はそもそもプリンスの当時のバンドであったレヴォリューションと一緒にやる予定ではなかった曲の一つという点が確認したい事実です。他のアーティストへの提供楽曲としてデモを渡したところ、David Zがアレンジした曲を気に入ったプリンスがさらに曲をアレンジして魅力的なものへと仕上げて成立したのです。

　当時のプリンスは大量に溢れ出る楽曲アイデアを誰が歌うかについて、作成する中で考えていたのだと思います。たとえば、日本を代表するプリンスのファンサイトを作成されているキッドさんのサイトにあるプリンスの提供楽曲一覧をみてください\*6。別名義でも様々な曲を様々なアーティストへ提供していることがわかります。そもそもプリンスは多作なアーティストということで知られており、生前ほぼ毎年のようにフルアルバムを出していた数少ないアーティストでした。基本的に、お気に入りの曲は自分で歌うので、そこから漏れたものあるいはその人に歌って欲しいものが提供されるわけです。たとえば、バングルズの「Manic Monday」の歌詞には性的な表現が含まれているのですが、この曲がそもそもアポロニア6への提供予定のものだったというような事情を踏まえると不思議ではありません\*7。このようにプリンスは提供相手に合わせて歌詞を書いている側面があります。こうした多作なプリンス特有の事情を踏まえた上で、そもそも「Kiss」は本人のお気に入りでも何でもなくマザラティに歌ってもらうためにデモを提供したという点は頭の片隅に置いても良いでしょう。プリンスはこの曲のデモ段階では少なくとも自分ではなく他の人が歌った方が魅力的になる可能性があるないし、自分が歌わなくても良いと判断した曲だったのです。

### 2. 映画の挿入歌としての「Kiss」

　次に「Kiss」がどのようにして世に出たかの事実についても確認しましょう。初出は本人が作成したモノクロ映画のサウンドトラック『Parade Music FROM THE MOTION PICTURE UNDER THE CHERRY MOON』です。『Under the cherry Moon』(1986)は恐らくファン以外では見たことのある人が少ないであろう本人監督・出演の映画であり、「Kiss」は劇中で使用されている1曲です。この映画『Purple Rain』のような大ヒットとはいかず、ラズベリー賞の受賞含め当時は酷評されていました。音楽の才能に恵まれたプリンスも素晴らしい映画は作れなかったわけです。この後も映画には何回か挑戦していますが、残念ながら興行的には全て失敗に終わっています。そして、記念すべき初監督作の映画のシーンの挿入歌として「Kiss」は発表されたのです。この映画のストーリーは大まかに次のようなものです。

> 舞台はフランスの南東部コート・ダジュール（英名：フレンチ・リビエラ）に位置するニース、富裕層の集まる高級リゾート地としても有名なこの地でピアニストとして働くクリストファー・トレイシー（プリンス）は”もう一つの顔”ジゴロ（プレイボーイ）としても有名で、魅惑の歌声と甘い視線で淑女からお金を巻き上げて生活していました。そんなある日、造船業を経営する大富豪アイザックの娘マリー・シャロン（クリスティン・スコット・トーマス）が21歳の誕生日に5千万ドルもの財産を相続するという情報を得ます。数多くの女性を手玉に取ってたクリストファーは相棒のトリッキー（ジェローム・ベントン）と共謀し搾取すべくメアリーに接近しますがメアリーは気にも止めません。その気の無いメアリーに色んな恋の罠を仕掛けるうちに次第にマリーにたいして恋心が芽生え、思惑が崩れクリストファーとの関係が悪化するトリッキー、そして娘の異変を感じた父親アイザックが動き出し・・・

[https://npg-net.com/discography/films/under-the-cherry-moon-86/](https://npg-net.com/discography/films/under-the-cherry-moon-86/)

　このあらすじからは、『Under the Cherry Moon』が名うてのプレイボーイが大富豪の令嬢を口説くという目立って新鮮味があるわけではないストーリーの映画であることが分かるでしょう。次に実際に「Kiss」が挿入されるシーンを見てみましょう。劇中でシャロンの"I Hate you"とのセリフに対してプリンス演じるジゴロのクリストファーが" I love you"と返し、その後は・・・みたいな感じ。詳しくは本編を見てください 。

[動画：映画『Under the Cherry Moon』での「Kiss」使用場面（YouTube）](https://www.youtube.com/watch?v=5PYUREobJew)

　このような映画のサントラであるという文脈から北村先生は「Kiss」を恐らく解釈していません。映画には北村先生が指摘するダイナスティにハマっているという女性は登場しませんし、そのような女性を必死になって口説いている男も登場していません。そもそも映画の舞台は1940年代のフランスで、曲の使用場面の設定はどちらかといえば、ジゴロ役のクリストファー演じるプリンスが少なくとも当該場面では令嬢をジゴロらしく口説こうとしている場面の一つとして描かれています。このように『Under The Cherry Moon』はそもそも『ダイナスティ』が放映されていた80年代の米国を舞台にした映画ではないのです。また、この映画では結果的にシャロンとクリストファーのお互いが燃え上がる関係になるため、一貫して男性の求愛を冷たくあしらっている女性は登場しませんし、必死の求愛が冷たくあしらわれる男性も登場しません。

　したがって、北村先生の解釈は映画のサントラの1曲ないし、あるシーンの挿入歌としてシーンと一緒に分析を試みる類のものではないと考えるのが自然でしょう。恐らく北村先生はプリンスの名曲のうちの一つの曲として「Kiss」を解釈しようという立場を打ち出しているのだと思います。この点は、そのような解釈の選択肢であることは特に問題ないように思えます。標準的には映画で使用されているシーンの分析などと併せて解釈するのが、映画の中の使用楽曲として捉えるなら望ましいのだと思います。しかし、映画として駄作、失敗作としての評価となっているもののサントラであれば、その曲にもネガティブな評価が下されやすくなるため、その曲の魅力が十分には分からないのではないかというのは一定の根拠のある主張でしょう。恐らくそのような点を分かっているからこそ北村先生は敢えて映画のサントラの楽曲という側面を切り離して解釈されているのだと思います。実際、「Kiss」はプリンスの数ある名曲の中でも屈指のものであることは疑いようがないものですし、楽曲だけに焦点を絞った解釈をというスタンスはそれはそれで筋の通ったものとして理解できます。なぜなら、先に確認したようにそもそも「Kiss」は映画で使用するという目的で作っていなかったからです。その点はマザラティへ提供する可能性があったという点から傍証できるでしょう。この点に関しては私も異論はありません。したがって、映画の挿入歌としてではなく、楽曲単体で解釈するという立場を取っていることはありうる解釈の選択肢の一つだと考えます。しかし、その作業に移る前にもう一つの映像作品であるミュージックビデオを確認します。私の見るところこの作品も当時のプリンスらしい要素が随所に現れているからです。

### 3. ミュージックビデオとしての「Kiss」

　さて、上記のように映画のサントラという文脈を離れた解釈が可能であるという点を認めた上で、もう一つの映像作品であるPVをみましょう。こちらも解釈する上でいくつかの手がかりを得られるものだと思われるからです。ちなみに、北村先生のツイートからは映像作品としての「Kiss」を解釈した可能性は「聴いて」という発言から恐らく低いと推測できます。なぜそうされたのかについては分かりません。この点は一旦脇に置いて、PVと曲の関係から考えてみましょう。映画として酷評された『Parede』でしたが、「Kiss」はこのサウンドトラックの中でシングルカットされ、PVも作られています。実際、この曲はいい作品だとプリンス本人は考えていたわけですが、当時のレコード会社の上層部などの意見はそうでもなかったようです。このPVは独特の世界観で良くも悪くもプリンスらしさに溢れています。なにわともあれ、まずはPVをみてください。

[動画：Prince「Kiss」ミュージックビデオ（YouTube）](https://www.youtube.com/watch?v=H9tEvfIsDyo)

　80年代中頃MTV全盛期の時代に突入していた当時PVはCDのセールを上げるためにも非常に重要なツールでした\*。そのため、楽曲の魅力を最大限にアピールできるPVを作ることはセールス戦略の一部として重要なはずで、「Kiss」もご多分に漏れず、原曲の世界観とマッチしたPVになっているように思えます。さて、皆さんはこのPVを見てどのような感想を抱くでしょうか。私がまず注目したいのは、PVの撮影セットが無駄を徹底的に削ぎ落としており、衣装や照明もシンプルでPVの登場人物もプリンス、ウェンディ、ダンサーの3名と最低限の人数で演奏やダンスの演出も徹底して無駄を削ぎ落としている点です。このような削ぎ落としたPVは当時大きな予算をかけて作られていた他のPVと比べるとチープなものに映るかもしれません。もちろん後の「Sign o' the Times」のように歌詞を流すだけというさらにシンプルなものもあるわけですが、「Kiss」もそれと変わらないくらいシンプルなものになっています。実際、ダンサーとプリンスそれぞれのダンス、二人でのダンス、ウェンディのギタープレイとその横で踊るプリンスでシーンの説明はほぼ尽きます。それぞれの登場シーンに何か特別凝った演出があるわけでもありません。ダンスにしてもマイケルジャクソンのようなムーンウォークやゼログラヴィティなどの印象的なムーブがあるわけでもありません。キメのスプリットは披露していますが、これもその場面に焦点を当てるようにしてビデオは撮られていません。こうしたシンプルで無駄を削ぎ落とすという映像の特徴は明らかに「Kiss」の楽曲の特徴を意識して作られているように思われます。次に楽曲の特徴を確認しましょう。

　「Kiss」は非常にシンプルな構造で音数も少ない楽曲です。録音で使用したトラックはわずか9つで、楽曲のミックスも5分で済ませたシンプルなものです。コード進行もシンプルで、楽器もほぼドラムマシーン、ギターとヴォーカルのみ、ベースやホーン、キーボードなどは登場しません。この曲は打ち込みのキック音をリヴァースをかけることでベースラインとして使用するというDavid Zによる冴えたアレンジとPrinceによるJBの「Papa's Got A Brand New Bag」ギターのリフの借用という要素で完成しています\*8。

[動画：James Brown「Papa's Got a Brand New Bag」（YouTube）](https://www.youtube.com/watch?v=rnDEr9R0snU)

　つまり、プリンスは無駄な要素を徹底して削ぎ落とし、必要最低限のものだけで楽曲を構成することで曲の魅力を最大限に発揮しているのです。「Kiss」は「When Doves Cry」と同様にベースレス、ドラムマシーンをうまく利用してベースラインを作るというアイデア、ファルセットの歌声というプリンスの得意技を惜しみなく注ぎ込んでいる楽曲です。このような楽曲の特徴は先に見たPVも無駄を削ぎ落とした最低限のものになっている点と対応関係を見出せるでしょう。そこには様々な余分なものを徹底して削ろうとするプリンスの意図があります。

　さて、次に考えたいのは、PVとしてみたとき、そこに何かストーリーらしくものがあるPVだったのかという問題です。たとえば、同時代にライバルであったマイケル・ジャクソンによるホラー映画オマージュの「Thriller」やウェストサイドストーリーオマージュの「Beat it」などとは同様に、そのようなストーリーがあるようなPVとして観れるでしょうか\*9。私の見るところシンプルなセットにプリンスとダンサーのダンスと若干気だるくギターをひくウエンディの映像が繰り返されるだけで、ストーリーはほぼ皆無なように見えます。少なくとも何かしら展開のあるストーリーがあるようには見えません。ダンサー役の女性はベールに覆われサングラスをかけており、匿名性が強調されています。それは歌詞中で容姿が重要ではないという点に対応しているとも言えるでしょう。お金のかかった派手な演出もないところからはお金は大事じゃないという歌詞の主張を裏付けるような演出とも取れるかもしれません。実際このPVの撮影費用はおそらく上記のマイケルジャクソンのものなどと比較すれば圧倒的に費用はかかっていないように見えます。もちろん『ダイナスティ』の映像などが流れることもありません。プリンスがダンサーに迫っているシーンはありますが、基本的に二人でのダンスシーンは戯れを楽しんでいるように見えるものです。さらに中盤は両者がシルエットでのダンスとなるシーンもあり、匿名性はさらに強調される瞬間まであります。冷たくあしらう女性と熱狂的に求愛する人は登場していないように見えます。PVの最後のシーンでは最初のシーンでプリンスがダンサー役の女性の肩越しにキスに対するつれない反応に涙を流すジェスチャーをしたのと対照的にダンサー役の女性がプリンスの肩越しに遊びでキスをしてプリンスが驚くリアクションを取るシーンで終わっています。つまりあしらわれ続けた訳ではないような反応で終わっていることになります。このようにPVからは楽曲の構成と併せて、シンプルな構成に徹しており、歌詞と重なり合うような演出もあり、何かしらのストーリーを演出しているようには見えません。仮にあったとしても結末は北村先生の考えているものと真逆です。

　しかし、PVの解釈では北村先生の主張する解釈として適切ではありません。なぜなら、北村先生自身が当該のツイートで「聴いて」と書いていることから、PVという映像作品として解釈したわけではないのだということを推測できるからです。そこで、次節では、楽曲のみでの解釈を試みます。ただし、その中でも歌詞に絞って検討します。この作業のために、プリンスの曲をいくつかのジャンルに分けた上で、実際に「Kiss」がどのようなジャンルに当てはまると考えられるのかを確認したいと思います。それを元に私の立場を明らかにすることになります。

### 4. プリンスの曲のジャンル分けについて

　私は「Kiss」をストーリーのある曲と解釈しません。この点に関する私の主張と根拠を曲のジャンルという観点から考えてみましょう。以下では分析美学と呼ばれている近年国内で森功次先生などが中心になって多数の訳本が出版され、国内でも研究が蓄積されてきている分野の議論を援用するかたちで、まず、プリンスの曲がどのようなジャンルに属するのか正確にしたいと思います。この点を明確化するためにノエルキャロル(2017)『批評について 芸術批評の哲学』の議論を参照しましょう。そもそも批評とはどのような営みと考えられるかについて、キャロルは次のような条件を挙げています。

> ここに含まれる作業[批評のこと]としては、記述(descripition)、分類(clasification)、文脈づけ(contextualization)、解明(elucidation)、解釈(interpretation)、分析(analysis)、そして価値づけがある。([ ]内はunoの挿入。)

ノエル・キャロル(2019)『批評について 芸術批評の哲学』、勁草書房、p.119

　この全てを満たす必要はないが、6つの条件のうちどれか1つと価値づけが何かしらの形で行われていれば、批評足りうるというのが、キャロルの主張です。キャロルによれば、批評というのは根拠に基づいた価値づけ（grounded evaluation）であるため、6つの作業どれかが行なわれていることで、価値づけの根拠が提出され、それによって価値づけが可能になるというものです。以下で、私が「Kiss」の解釈で試みようとするのは分類とそれによる価値づけの2つにあたるでしょう。つまり、楽曲の歌詞の分類を通じて、「Kiss」がストーリーのある曲ではないタイプの曲であるということを主張したいと考えています。これによって、「Kiss」はストーリーを描くというよりも歌い手の価値観を提示している楽曲であると主張し、この曲の価値づけを図りたいと考えています。この作業に移る前に、まず分類(Classification)についてキャロルの議論を敷衍しましょう。そもそも芸術作品は様々なカテゴリーをとって現れるものです。たとえば、それぞれの作品は絵画や彫刻、音楽、文学、演劇、ダンスなどなど様々なカテゴリーがあります。そして、それぞれのカテゴリーの中でさらに下位のカテゴリーとして、ジャンルや様式などがあります。評価対象を適切なカテゴリーに設定することは大切な作業です。どのカテゴリーに属するかを明らかにすることは、その作品をどのように評価すべきかを判定するために大切な作業からです。つまり、その作品のカテゴリーが明らかにすることで、その作品が成功しているか、失敗しているかが明らかになるのです。たとえば「Kiss」をファンクではなく、クラシックというカテゴリーに属するものとしてみると、クラシックというジャンルからは低い評価しか与えられないでしょう。ファンクというジャンルのなかに、「Kiss」を位置づけることで、革新的な楽曲として評価されることになります。このようにカテゴリーを特定することで、その作品を評価する基準が設定可能となります。そして、それに従って、批評をうまくできるようになるからです。もちろん、このようなカテゴリーに訴える立場に対して反論もあります。そもそも新しい芸術形式(e.g., 写真、映画、ビデオ、CG)が次々登場しているために、その芸術形式に何を期待するかについて、既存のカテゴリーを参考にできないし、そのような既存のカテゴリーが期待するようなものとも結びついていないのではないかというようなものです。このような反論に対してキャロルは次のような再反論をしています。(まだ途中なので後で書き上げる予定。ここは今回書き上げます。)

　このように分類することは評価基準と直結するために、批評において必要な作業となるのです。したがって、この点で私は明確に北村先生の解釈に疑問を覚えます。だからこそ根拠が知りたいというわけです。

　さて、次節では私が「Kiss」はプリンスの楽曲の中でどのようなジャンルに属すると考えているのかを以下で確認しましょう。(まだ途中なので後で書き上げる予定。というかこの箇所は他のプリンスの曲の歌詞解釈とあわせて包括的に分類してみたほうがいい気がしてきています。なのでできるだけどのような歌詞のパターンがあるのかを確認してから再度別原稿を書いた方が適切ですね。プリンスのいくつかの楽曲を取り上げて、ある種のプリンス像を描いてみようと思います。)


### 5. 価値観表明としての「Kiss」の歌詞解釈

　さて、それでは私は「Kiss」をどのような曲と考えるかについて、以下で述べていきましょう。私はこの曲を歌い手が性愛の相手に何を求めるのか、つまり、どのような価値観が必要なのかを述べている歌と考えます。つまり、ある種の価値観の表明です。その際にキスが性愛において非常に大切なものを担っているという宣言だと考えます。その意味でこの曲は「D.M.S.R」というあまりに有名なプリンスの価値観と同様の価値観が全面的に出ている曲と共通点を持つようなものとなっています。しかし、それは「ダンス」、「ミュージック」、「セックス」、「ロマンス」こそ俺が求めているものなんて宣言ではありません。そのような複数の要素は過剰であると言えるような、一つの事柄について極めて限定的で余分を削ぎ落とした主張になっています。また、そのようなセックスやキスの過程の具体的な描写はありません。それは「Little Red Corvette 」や「The Ballad Of Dorothy Parker」といった歌詞にストーリーがあるのと比べれば明白です。さらに「Lady cab dreiver」のように合間の寸劇で残念な男性が果てるまでの過程を描いているようなものでもありません。これらの曲には時間の経過とともにどのような顛末を辿ったのかが明確に描かれています。これに対して「Kiss」では何を相手に求めているのか、求めないのかについてのいくつかの価値観が提示されているだけでストーリーはありません。
　さて以下では精力的にプリンスの歌詞を日本語に訳されているprince510さんの [http://prince510.blog.fc2.com/blog-category-11.html](http://prince510.blog.fc2.com/blog-category-11.html)  の訳を参照にしつつ、適宜区切りながら解釈を書いてみます。私が注目にしたいのはいくつかの価値観の削ぎ落とすことで、歌い手の独特な価値観を浮かび上がらせるという手法です。まさにこの楽曲の構造ともマッチしています。つまり、ありとあらゆる不要なものを削ぎ落としすことを通じて、その曲の魅了を最大限に提示するという楽曲構造と歌詞が合致しているのです。　
　まず、冒頭「美人じゃなくてもいいというYou don't have to be beautiful」です。刺激的ですね。歌い手にとって容姿はさして問題ではないという宣言です。別に美人だから悪いとも言っていません。そこにさして価値を見出さないということで容姿という価値観を性愛にとって本質ではないと削るわけです。では何が大切かという積極的な主張が出ます。それは、「君の身体さえあればいい I just need your body, baby」という貴女の身体こそが性愛にとって大切であると宣言されています。性愛においては身体的な接触こそが大切なので、身体こそ容姿の問題よりも大切なのだという価値観を提出しているのです。それはそうですね。相手なしに性愛は成立しません。そして、その宣言のために敢えて容姿の価値観重視を削るところから入るというトリッキーな始まりをとっている訳です。ミニマルな構成の楽曲構造と合致していますね。このようにある種の価値観をとりあげ、それは性愛にとって大切でないことを削ぎ落とす作業と何が残るのかを歌詞全体を通して提示することで、最終的に残ったものは何かと問われたときには身体、時間、キスの3つの要素だけで、それこそが大切なのだというまさにこの時期のプリンスらしいミニマルな価値観の提示にこの曲の歌詞の魅力があります。そして、そのKissがいかにポジティブな価値を持つか明らかにする瞬間に印象的なリフを挿入するという心憎い演出になっています。この観点から最後まで歌詞をじっくりと検討していきましょう。

　次に何を削るのでしょうか。経験です。経験は必要ない。あっても良いけど、そこでがポイントではない。経験は合っても良いけど、それは問題ではない。経験なんてものは歌い手についてくれば何とかなるのだというリードするのはあくまで歌い手で、一から十まで全て教えてあげるいう宣言です。

　次もある価値観を削ります。「彼女になるのに金持ちじゃなくてもいい You don't have to be rich to be my girl」つまり、性愛関係において金銭は重要な要素ではないという主張です。金銭が性愛においては不要なものんであるとして削られます。さらに、「クールじゃなくていい。You don't have to be cool to rule my world」とあります。これもある種イケているといった要素を不要としていることを宣言しているでしょう。これは先の容姿の部分に加えて、態度的な部分を不要としていると読めるでしょう。そして、ここからが面白いのですが、そうした諸々を削ったとしても「私の世界を支配するrule my world」ことは可能な訳です。じゃあ何が大切なのと言われれば「特別なサインなんかない　俺は君とピッタリ相性がいい俺は君と特別な時間と…Kissが欲しいだけAin't no particular sign I'm more compatible withI just want your extra time and your...Kiss」何かピンとくるような特別なサインなんて必要とはしておらず、キスと時間だけが必要と言っている訳です。削りに削った結果がそれだけなのかという訳ですが、そこにまさに楽曲の構造とマッチした快楽が味わえる訳ですね。これで一旦サビが終わります。さらに、同様に不要な価値を削りつつ、同様の主張がなされます。

~~以下は未完です…~~

　このようにいくつかの歌い手の持つ必要最小限の価値観が提示されており、それは極限までに無駄な音を削ぎ落とすことではじめて表現されるという歌い手の価値観の表現ではないでしょうか。

### 6. 物語としての「Kiss」の歌詞解釈

　さて、最後に補足として北村先生の歌詞の解釈に入っていきましょう。さて、繰り返しになりますが、恐らく北村先生は「Kiss」をストーリー仕立ての曲として解釈しています。再度北村先生のツイートを引用します。

[Xの投稿を見る](https://x.com/i/web/status/1932627042719445151)

　残念ながら、上記の北村先生の一つのツイートだけからは、解釈の根拠や過程が正確に分かりません。何よりも、最大の疑問は北村先生が以下の3つの主張を組み合わせて、描いているであろうストーリー、歌い手が女性を必死で口説こうとしているのに対してつれない態度を女性がとっている曲として聴けるのかという点です。

1. ダイナスティにハマっている女性が曲中の登場人物の一人である。
2.  歌い手が、女性に必死の求愛をしている。
3.  女性は歌い手の求愛に興味がない。

　北村先生は「Kiss」をストーリーのある曲として解釈しており、それが上の三つの要素から成立していると主張しています。まず、北村先生の主張1の『ダイナスティ』にハマっている女性が曲中の登場人物の一人であるはどうでしょうか。『ダイナスティ』の箇所はのちに『Sex And The City』など当時の流行のドラマに変更がなされている箇所です。実際に以下のライブでは歌詞の変更が加えられています。惚れ惚れするような素晴らしいパフォーマンスですね。ブラックウェル先生が元気にドラム演奏しているのを観てちょっぴりうるっときました。キャンディ先生はいつでもセクシーですね！大阪で生で見れて感動しました！僕がサックスをするきっかけになった憧れの人です！！！　

[動画：Prince「Kiss」ライブ・パフォーマンス（YouTube）](https://www.youtube.com/watch?v=O-8J8YMLQck)

こうした点を踏まえると「Kiss」の歌詞の中で『ダイナスティ』という作品が持つ内容はさほど重要ではないことが推測できます。それに対して「Little Red Corvette 」では車の車種を変更することは考えられません。「キャデラック」や「ジープ」などに変更して歌うことはまずないのではないでしょうか。車種と女性のイメージをマッチさせることで、曲の魅力を引き立てているのです。それに対して「Kiss」の歌詞中の『ダイナスティ』という単語はそもそもライブでくすぐりとして使われており、当時の流行りなどを挿入する箇所に過ぎず、曲中のキーワードではありません。さらに、北村先生は『ダイナスティ』にハマっている女性と述べていますが、それがそもそもハマっていると読み込めるフレーズはありません。さらに、求愛者はどちらかといえばそうしたステレオタイプの性愛関係を批判するためにファルセットを使用して、中性的なイメージを演出しているととったほうが自然なように思われます。そうすることで、何でもありなのだという主張を帯びていると考えた方がプリンスらしいのではないかと私は思います。そもそもキャラクターを登場させるときは「The Ballad Of Dorothy Parker」のウェイトレスのように明確に歌詞で特徴を浮かび上がらせているのに対して「Kiss」ではそのような人物描写は皆無です。さらに、必死の求愛をしている歌であると北村先生は述べていますが、歌詞のどこから必死の求愛なのかがわかりません。前節で私が述べたように、あれもいらない、これもいらない、これだけあればいい、これこそ大切なんだという内容の歌詞で果たして必死の求愛になるのでしょうか。それよりはあれもある、これもある、全部ある、だからあなたの欠点を含めて全部好きと言ったパターンの方が必死さを覚えるのではないでしょうか。しかし、この点は、はっきりわかりません。私の経験が少ないだけかもしれません。3も同様です。求愛に興味がないとありますが、そもそも「Kiss」には歌い手以外のセリフがありません。恐らくそこから求愛に興味がないと北村先生は解釈しているのでしょうが、それは非常に踏み込んだ解釈になるため、どのような根拠からそのように述べているのかは丁寧な説明が必要になってくるように思われます。私にはその点は読み込めませんでした。こうしてみると1−3それぞれの主張にどのような根拠があるのか明確にできない限りストーリーとして「Kiss」を聴くことは困難なように思われます。ただし、これらの点については北村先生や他の方々の応答によって疑問点が解消され、ストーリーがある曲であると解釈できるかもしれません。そうなるとまさに一見すると何の変哲もない歌詞に対して全く異なる解釈が可能になるという意味でよりプリンスの素晴らしさを感じれるかもしれませんね。

### 7. おわりに

　さて、私の「Kiss」解釈はどのように思われたでしょうか？楽しんで頂けましたか？私も北村先生と同じく映画のサントラであるという点に踏み込まず、プリンスの数ある曲の一つとして解釈するとどうなるかというものです。私の解釈はプリンスのその他の曲と比較して、曲の歌詞にストーリーがあると言えるのかという観点からプリンスの曲の中でのジャンル分けを行った上で、歌詞を見ていくという形のものでした。結果としてストーリーがある歌詞ではなく、ある種の価値観を歌い手が提示していると解釈しました。それに対して北村先生は「Kiss」に複数の登場人物がいること、そして、それらの人物像が描かれているとした上で、男性が女性に求愛し、女性は冷たくあしらっているストーリーを持つという解釈です。ただし、北村先生の解釈は根拠含め情報量が圧倒的に少なく、どのような過程を経て、先の引用のような解釈になったのかはほぼ分からないものです。6で可能な限り意図を読み取ろうと試みたのですが、それでもソースが分からないこともあり、不十分なことは否めません。冒頭の繰り返しになりますが、北村先生からはぜひ、その解釈過程や根拠を詳しく教えて欲しいですね。何より魅力的な解釈を皆さんでもぜひ考えてみてください。教えてくださると私が喜びます。最後になりますが、プリンスは名曲がたくさんあり、どれも素晴らしいので、みなさんにも楽しんで欲しいです。きっといま聴いてもいろいろな発見があるはずですし、少なくともいまでも私にはあります。ぜひ「Alphabet St.」のリフや「The Ballad Of Dorothy Parker」のベースで痺れるような密室ファンクを体験したのちに、「Cloreen Baconskin」みたいなミニマルファンクを楽しんで欲しいと思う次第です。今回の記事は日記ではなく、自分が好きなものについていま一度丹念に調べつつ、時間をかけて書くということを楽しめたのも良かったですね。自分がいかにしてプリンスを堪能していたのか、好きなのかを少し明確にできた気がします。またプリンスについて幾つかの曲を取り上げつつまとまったものを書いてみる予定です。あくまで予定！おしまい。

2025/7/7追記『Under The Cherry Moon』の人名の誤りのご指摘を江口某さんから受けたため訂正しています。ありがとうございます。恐らくその他誤字脱字等諸々あるので、ご指摘ください。

2025/7/ 

---

**脚注**
\*1 たとえば [https://rollingstonejapan.com/articles/detail/25839/2/1/1](https://rollingstonejapan.com/articles/detail/25839/2/1/1) を参照(2025/7/6 最終アクセス)。　

\*2 [https://ja.wikipedia.org/wiki/KISS\_(%E3%83%97%E3%83%AA%E3%83%B3%E3%82%B9%E3%81%AE%E6%9B%B2)](https://ja.wikipedia.org/wiki/KISS_\(%E3%83%97%E3%83%AA%E3%83%B3%E3%82%B9%E3%81%AE%E6%9B%B2\))　(2025/7/6 最終アクセス)。　

\*3 [https://researchmap.jp/saebou](https://researchmap.jp/saebou)　(2025/7/6 最終アクセス)。　

\*4 たとえば、スティングのソロ活動開始当初の屈指の名曲「Englishman In New York」をスティングが書いたのではなく、プリンスが書いたと事実を誤って認識したとしましょう。仮にプリンスが「Englishman In New York」のような曲を書いたと誤った事実を認識すると、プリンスの本来の作風とはかけ離れており、プリンス異色の名曲で・・・といった解釈を許容する可能性が出てきます。しかし、そうではなく80年代中頃にポリスを解散してソロ活動へと移ったスティングが当時NYに在住していたクエンティン・クリスプをモチーフに歌詞を書いたものであるとして、初めてその作品の経緯含めた背景事情によるジャンルやカテゴリー分けを踏まえた解釈が可能になってくるでしょう。

\*5 このエピソードはいくつかのブログでも取り上げられています。海外のサイトなどではDavid Zのインタビュー記事もあがってたはずなので、掘ればきっと見つかるはず。加筆時に見つけたので追加しています。ちなみにDavid Zはプリンスと同じミネアポリス出身の人で彼がプロデュースした Lipes inc は誰でも耳にしたであろう名曲の「ファンキータウン」を世に残しています。
[https://oneh.blog.jp/prince/kiss.htm](https://oneh.blog.jp/prince/kiss.htm)　[https://popups.hatenablog.com/entry/2019/10/22/070008](https://popups.hatenablog.com/entry/2019/10/22/070008)　[https://www.soundonsound.com/techniques/classic-tracks-prince-kiss](https://www.soundonsound.com/techniques/classic-tracks-prince-kiss) 　　(上記のサイト全て2025/7/6 最終アクセス)

\*6 [https://npg-net.com/pfamily-conect/](https://npg-net.com/pfamily-conect/)　(2025/7/6 最終アクセス)

\*7 [https://oneh.blog.jp/prince/manic-monday.html](https://oneh.blog.jp/prince/manic-monday.html) (2025/7/6 最終アクセス)

\*8 [https://popups.hatenablog.com/entry/2019/10/22/070008](https://popups.hatenablog.com/entry/2019/10/22/070008) (2025/7/6 最終アクセス)

\*9　[https://ja.wikipedia.org/wiki/スリラー\_(ミュージック・ビデオ)](https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%AA%E3%83%A9%E3%83%BC_\(%E3%83%9F%E3%83%A5%E3%83%BC%E3%82%B8%E3%83%83%E3%82%AF%E3%83%BB%E3%83%93%E3%83%87%E3%82%AA\))　　　　
　　 [https://ja.wikipedia.org/wiki/今夜はビート・イット](https://ja.wikipedia.org/wiki/%E4%BB%8A%E5%A4%9C%E3%81%AF%E3%83%93%E3%83%BC%E3%83%88%E3%83%BB%E3%82%A4%E3%83%83%E3%83%88) 　                                        
        (上記のサイト全て2025/7/6 最終アクセス)
