---
title: "Schramme の健康概念についてのノート"
page-layout: full
---

***

[Schrammeの健康概念](https://doi.org/10.1093/phe/phad017)についてのノート。今度の学会発表に使う予定なのでメモ書きを残す。この論文を x で言及している人がいて、見たときに気になってダウンロードしておいたやつ。紹介してくれた人に感謝。
Schrammeは健康・疾病・精神医学の哲学を研究している哲学者。現在はリヴァプール大学の教授らしい。この論文はWHOの健康概念についての解釈がメイン。面白いのは哲学的な議論だけではなく、成立過程に関する資料も丁寧に追っているあたり。こういうのは手堅い研究という感じ。

<br>

目次は以下の通り。ハイライトは3でここの整理が手際良くできていていいところ。4もSchrammeの主張。

<br>

1. 序論

2. WHOの定義への批判

3. WHOの健康定義を解釈すること

4. なぜ私たちはホリスティックな健康と完全無欠の健康を区別する必要があるのか

5. 結論

<br>

以下は論文についてのメモ書き。

そもそものスタートはWHO(1948)の健康の定義と基本的人権の定義を組み合わせるとある問題が生じるという批判がダニエル・キャラハン(1973)らによって行われてきた。
以下ではキャラハンらが指摘する問題の導出過程をまとめよう。

<br>
1. 「健康とは完全な身体的・精神的・社会的ウェルビーイングの状態であり、単に疾病または虚弱が存在しないことではない。Health is a state of complete physical, mental and social well-being and not merely the absence of disease or infirmity."」(WHO, 1948:100)

<br>
2. 「到達可能な最高水準の健康を享受することは、人種、宗教、政治的信条、経済的、または社会的条件によるいかなる差別もなく、すべての人間の基本的権利の一つである」(WHO, 1948:100)。

<br>

この二つの定義を出発点に次のような推論を考えよう。

<br>

1. 基本的人権がない人間は存在しない。(WHOの定義)

2. 基本的人権より到達可能な最高水準の健康を享受する権利がある。(WHOの定義)

3. 健康は完全なウェルビーイングの状態である。(WHOの定義)

4. 完全なウェルビーイングとは、健康について到達すべき理想的・最高の状態である。（completeの完全主義的解釈）

5. 完全なウェルビーイングの状態でないなら、到達可能な最高水準の健康ではない。(4の対偶)

6. 到達可能な最高水準の健康を享受する権利がないなら、基本的人権に反する。(2の対偶)

7. 基本的人権は遵守すべきなので、権利を享受できていないのは問題である。(6より)

8. 健康ではない場合それを改善することは、医療・保健の役割である。(仮定)

9. 完全な健康という理想に届かない場合は、人々の健康を向上しなければならず、そのための医療の介入が正当化される。(5,7,8)
<br>

大まかにこのような構造の推論によって批判が向けられてきた。8の仮定についてはSchrammeが扱わない。Schrammeが問題とするのは4である。このWHOの定義の解釈について、SchrammeはWHOの健康概念の定義はそもそも二通りの解釈が可能であることを主張する。この辺りの経緯で資料にあたってありうる解釈を提示するのだが、それは原文にあたって確認してほしい。成立経緯に関する資料にあたって丹念に調査した文献学的な手法の箇所である。公衆衛生の専門家たちの参加による影響などを丁寧な調査から指摘しているが、この点は省略。
そのような文献的な資料から、Schrammeが提示するWHOの健康の定義に関する解釈は次の二つがあり得ることを述べている。

<br>
1. perfect well-being説 : 健康というのは、**完全な**身体的・精神的・社会的ウェルビーイングの状態を意味する。健康についての完全無欠解釈。

<br>
2. exhaustive well-being説 : 健康というのは、身体的・精神的・社会的ウェルビーイングの**全ての**構成要素を含んだ状態を意味する。健康についてのホリスティックな解釈。

<br>

まさにcompleteの解釈が問題となるわけである。ここは一旦Schrammeの解釈を傍に置いて、英文法の解釈でどのように取れるのかを確認しておこう。
英文法的なところを解釈すると、completeはphsyical, mental and social それぞれのwell-beingを修飾すると取れる。そして、completeは程度を表す類のものではない。つまり、欠けていてはならないことを強調する語になっている。さらに、completeはstateを直接修飾しているわけではない。したがって、状態そのものが完全ではなく、ウェルビーイングの内容がcompleteである状態を意味すると取るのがどちらかといえば自然である。ここまでは、英文法のお話。さて、これで終わると面白くはないので、Schrammeが文献学的な根拠を除きどのような根拠で2の解釈を支持するのかもう少し詳しく検討しよう。Schrammeがホリスティック解釈を支持する根拠は大体次のとおり。

<br>

1. 健康は多くの側面を持つウェルビーイングの状態である。すなわち、身体的な、精神的、社会的側面それぞれを持つ。

2. 健康は二値的なものではない。つまり健康と不健康は簡単に裁断できない。段階があり、グラデーションがあるものとして捉えるのが自然である。

3. ホリスティックな健康概念は健康の維持を目的にする。

4. WHO,1986のオタワ憲章との整合性。「健康とは、日常生活のための資源であって、生きることの目的ではない。健康とは、身体的能力と同様に、社会的・個人的資源を強調する肯定的概念である」。つまり、健康は生活を送るための道具・資源であって目的ではない。

<br>

1はそのままである。身体的な健康は重要である。たとえば、足を骨折していたら松葉杖なしで歩くことはできない。精神的な健康は昨今話題に上がることが多いだろう。うつ病なら、就労が難しいといったことはわかりやすい。社会的な健康は重要だろう。退職した後、趣味などがないため、様々な人との交流がなくなれば、認知機能が低下するといった話はよくあることである。ただし、社会的要素を健康の「構成要素」とするのか、健康を左右する「決定因子」とするのかには問題が残る。Schramme自身も第4節でこの境界の曖昧化をholistic healthの問題点として認めている。これらの議論を踏まえれば、健康といってもそれは複数の要素からなる概念だという主張は自然だろう。2は健康というのがそもそも健康と不健康と綺麗に裁断できるものではないという見解である。たとえば、血圧などは食生活や遺伝などの要因も加味しないと数字だけでは簡単に、健康不健康と言い切れないだろう。3はまさに医療がどこに介入するかの場面で出てくるだろう。たとえば、ワクチンの接種はその典型だろう。4はWHOが健康というものを目的ではなく、目的達成のための道具、資源として捉えるということを明示していることになる。そのため、その人にとっての目的が達成される程度の健康であれば良いという含意があるだろう。
このような根拠に基づいて、completeという語が意味するのは包括的 exhaustive の方であるという議論を展開している。

<br>
さらに、完全無欠な健康ではなく、ホリスティックな健康で解釈したときにどこで問題が生じるのかまで敷衍されている点も好感度が持てる。勉強になった。そもそも内容が正確に読めているのかといった点についてはきちんと冒頭のリンクから原文に飛んで確認してください。おしまい。
