---
title : 作った料理
---

特に何か特別なレシピや作り方を丁寧に書いているわけではない。

単に作った料理をあげて再利用できるようの備忘録。

# 2026年
<br>
# 鶏のフリカッセ
[フリカッセ](https://www.otory.jp/blogs/%E6%96%99%E7%90%86%E7%94%A8%E8%AA%9E/%E3%83%95%E3%83%AA%E3%82%AB%E3%83%83%E3%82%BB)は、フランスのロワーヌ地方のメーヌ地域の冬の家庭料理。

バターで炒めた玉葱などの野菜と鶏肉を生クリームで煮込んだ白い煮込み料理のこと。 

家庭料理ということで各家庭でアレンジをすることもしばしば。

メインに使う具材が決まっているわけではないらしい。

一般的にはチキンを使ったフリカッセである「フリカッセ・ド・プーレ」が多い。

仔牛・仔羊や魚介類を使うこともある。

鶏肉と野菜をクリームで煮込んだ料理といえば、シチューがあるけれども、シチューとの違いは、煮込む前にお肉を炒めるかどうか。

焼いてから煮込むことで旨味が中に閉じ込められ、お肉の味がより美味しく味わえる肉料理。

シチューはどちらかというと、スープを味わうお料理です。

フリカッセ(fricassee)は、ソテー(saute:炒めるという意味)とかシチュー(stew:煮込むという意味)も同じですが、調理方法のことらしい。 


## 材料と簡単な工程

鶏もも肉：300〜350g、今回は1枚まるまる焼いた。前日の夜にキッチンペーパーでまず水分をとった上で、塩を0.8％くらいの量で振ってさらに一晩寝かせる。

作る20分前くらいで、取り出してまたキッチンペーパーで水分をとる。皮を下にしてして5、6分中火で火を入れる、入れた後取り出して休ませる。

舞茸：1パック　炒める。焦げ色をつけるくらい。中火。

しめじ：1/2〜1パック　炒める。中火。

ほうれん草：1/2束　ゆがくだけ。

玉ねぎ：1個、薄く切る。バターと炒める。中火。

にんにく：1片、微塵切り、玉ねぎと一緒に一瞬炒める。

白ワイン：100ml、玉ねぎとニンニクを炒めたタイミングで、デグラッセで使う。今回はチリのソーヴィニヨンブランを使った。

水：100ml、入れて休ませた鶏を戻す今度は皮を上にして、ぐつぐつ煮込む感じ。10−12分くらい。その後もう一度鶏肉を出して休ませる。

生クリーム：150ml、キノコ類を戻した後入れる。コトコト煮込んでソースを作る3分くらい。

バター：15g

オリーブオイル：小さじ1、最初に鶏に火を入れるタイミングで使う。油はあとは鶏皮のものだけでOK。

黒胡椒：適量

<br>
ほぼこのレシピ。小麦粉は使わずにやったので、本当は入れた方が良いと思う。今回のものは出来としてはまずまず。

それぞれの工程の素材の火入れとワインのデグラッセがポイントだと思う。

ほうれん草を鍋で軽くゆがく以外は全て同じフライパンで調理することで旨みを全てうまく利用できる。

<br>

[トップへ戻る](../site/index.qmd)