<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>学会分類・ガイドライン・規格</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ba8f7c244c1f50cbf6c6a3aa3874339a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "一致なし",
    "search-matching-documents-text": "一致した文書",
    "search-copy-link-title": "検索へのリンクをコピー",
    "search-hide-matches-text": "追加の検索結果を非表示",
    "search-more-match-text": "追加の検索結果",
    "search-more-matches-text": "追加の検索結果",
    "search-clear-button-title": "消去",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "検索",
    "search-label": "サーチ"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-BTBHJJ9F71"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-BTBHJJ9F71', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
          <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../site/index.html"> 
<span class="menu-text">home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../site/research.html"> 
<span class="menu-text">resarch</span></a>
  </li>  
</ul>
          <div class="quarto-navbar-tools">
</div>
            <div id="quarto-search" class="" title="サーチ"></div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">目次</h2>
   
  <ul>
  <li><a href="#収録一覧" id="toc-収録一覧" class="nav-link active" data-scroll-target="#収録一覧">収録一覧</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">学会分類・ガイドライン・規格</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>最終更新日：2026年9月24日</strong></p>
<p><strong>30件／国内由来 11件。</strong> 臨床分類、表示・食品規格、官能評価規格、意思決定、衛生管理を区別して参照する。</p>
<p>「国内」は日本の発行・提供機関を指す。ISO規格は日本語概要があっても国際資料に分類した。</p>
<section id="収録一覧" class="level2">
<h2 class="anchored" data-anchor-id="収録一覧">収録一覧</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>番号</th>
<th>地域</th>
<th>年</th>
<th>資料・論文</th>
<th>種別</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>01</td>
<td>国内</td>
<td>2021／Q&amp;Aは2026-08追加まで公式一覧で確認</td>
<td><a href="#ref-01">日本摂食嚥下リハビリテーション学会嚥下調整食分類2021</a></td>
<td>必読・学会分類／本文無料</td>
</tr>
<tr class="even">
<td>02</td>
<td>海外・国際</td>
<td>2019 v2.0（参照版。現行版との照合を要する）</td>
<td><a href="#ref-02">Complete IDDSI Framework: Detailed Definitions</a></td>
<td>必読・国際分類／公式公開資料</td>
</tr>
<tr class="odd">
<td>03</td>
<td>海外・国際</td>
<td>2019-07-31</td>
<td><a href="#ref-03">Testing Methods for use with the IDDSI Framework</a></td>
<td>必読・測定手順／本文無料</td>
</tr>
<tr class="even">
<td>04</td>
<td>国内</td>
<td>自主規格・版情報は公式案内で確認</td>
<td><a href="#ref-04">ユニバーサルデザインフード自主規格</a></td>
<td>必読・業界自主規格／概要無料</td>
</tr>
<tr class="odd">
<td>05</td>
<td>国内</td>
<td>随時更新／2026-09確認</td>
<td><a href="#ref-05">特別用途食品：えん下困難者用食品・とろみ調整用食品</a></td>
<td>必読・行政制度／公開資料</td>
</tr>
<tr class="even">
<td>06</td>
<td>国内</td>
<td>随時更新／2026-09確認</td>
<td><a href="#ref-06">スマイルケア食（新しい介護食品）</a></td>
<td>行政の選択支援枠組み／公開資料</td>
</tr>
<tr class="odd">
<td>07</td>
<td>国内</td>
<td>現行掲載版／2026-09確認</td>
<td><a href="#ref-07">そしゃく配慮食品の日本農林規格（JAS）</a></td>
<td>国家規格／本文無料</td>
</tr>
<tr class="even">
<td>08</td>
<td>国内</td>
<td>2019／訂正2021</td>
<td><a href="#ref-08">摂食嚥下障害の評価2019</a></td>
<td>必読・評価資料／本文無料</td>
</tr>
<tr class="odd">
<td>09</td>
<td>国内</td>
<td>2026年度版</td>
<td><a href="#ref-09">嚥下造影の手順2026年度版</a></td>
<td>更新資料・検査手順／本文無料</td>
</tr>
<tr class="even">
<td>10</td>
<td>国内</td>
<td>2021改訂</td>
<td><a href="#ref-10">嚥下内視鏡検査の手順2021改訂</a></td>
<td>検査手順／本文無料</td>
</tr>
<tr class="odd">
<td>11</td>
<td>国内</td>
<td>2024</td>
<td><a href="#ref-11">嚥下障害診療ガイドライン2024年版</a></td>
<td>必読・診療ガイドライン／公式案内、本文入手条件確認</td>
</tr>
<tr class="even">
<td>12</td>
<td>海外・国際</td>
<td>更新型／2026-09確認</td>
<td><a href="#ref-12">Adult Dysphagia — Practice Portal</a></td>
<td>必読・臨床実践情報／公開</td>
</tr>
<tr class="odd">
<td>13</td>
<td>海外・国際</td>
<td>2024公開版</td>
<td><a href="#ref-13">Position paper on the use of thickened fluids in the management of people with swallowing difficulties</a></td>
<td>必読・ポジションペーパー／本文無料</td>
</tr>
<tr class="even">
<td>14</td>
<td>海外・国際</td>
<td>2021</td>
<td><a href="#ref-14">Eating and drinking with acknowledged risks: Multidisciplinary team guidance for the shared decision-making process (adults)</a></td>
<td>必読・多職種意思決定指針／本文無料</td>
</tr>
<tr class="odd">
<td>15</td>
<td>海外・国際</td>
<td>2022</td>
<td><a href="#ref-15">ESPEN practical guideline: Clinical nutrition and hydration in geriatrics</a></td>
<td>必読・実践ガイドライン／学会公開版あり</td>
</tr>
<tr class="even">
<td>16</td>
<td>海外・国際</td>
<td>2024更新</td>
<td><a href="#ref-16">ESPEN guideline on nutrition and hydration in dementia – Update 2024</a></td>
<td>近年・診療ガイドライン／学会公開版あり</td>
</tr>
<tr class="odd">
<td>17</td>
<td>海外・国際</td>
<td>2021</td>
<td><a href="#ref-17">European Stroke Organisation and European Society for Swallowing Disorders guideline for the diagnosis and treatment of post-stroke dysphagia</a></td>
<td>疾患別ガイドライン／公開版あり</td>
</tr>
<tr class="even">
<td>18</td>
<td>海外・国際</td>
<td>2021</td>
<td><a href="#ref-18">Diagnosis and treatment of neurogenic dysphagia – S1 guideline of the German Society of Neurology</a></td>
<td>疾患領域別指針／本文無料</td>
</tr>
<tr class="odd">
<td>19</td>
<td>海外・国際</td>
<td>2001／オンライン情報更新型</td>
<td><a href="#ref-19">International Classification of Functioning, Disability and Health（ICF）</a></td>
<td>必読・国際分類／公式情報公開</td>
</tr>
<tr class="even">
<td>20</td>
<td>海外・国際</td>
<td>2021／NG197</td>
<td><a href="#ref-20">Shared decision making</a></td>
<td>意思決定ガイドライン／本文無料</td>
</tr>
<tr class="odd">
<td>21</td>
<td>海外・国際</td>
<td>2017</td>
<td><a href="#ref-21">ISO 6658: Sensory analysis — Methodology — General guidance</a></td>
<td>必読・官能評価規格／概要無料、規格本文別途</td>
</tr>
<tr class="even">
<td>22</td>
<td>海外・国際</td>
<td>2023</td>
<td><a href="#ref-22">ISO 8586: Sensory analysis — Selection and training of sensory assessors</a></td>
<td>近年・評価者選抜と訓練／概要無料</td>
</tr>
<tr class="odd">
<td>23</td>
<td>海外・国際</td>
<td>2007／追補2014、改訂作業中の表示を確認</td>
<td><a href="#ref-23">ISO 8589: Sensory analysis — General guidance for the design of test rooms</a></td>
<td>試験環境規格／概要無料</td>
</tr>
<tr class="even">
<td>24</td>
<td>海外・国際</td>
<td>2016</td>
<td><a href="#ref-24">ISO 13299: Sensory analysis — Methodology — General guidance for establishing a sensory profile</a></td>
<td>必読・官能プロファイル規格／概要無料</td>
</tr>
<tr class="odd">
<td>25</td>
<td>海外・国際</td>
<td>2014／追補2020</td>
<td><a href="#ref-25">ISO 11136: Sensory analysis — Methodology — General guidance for conducting hedonic tests with consumers in a controlled area</a></td>
<td>必読・消費者嗜好試験規格／概要無料</td>
</tr>
<tr class="even">
<td>26</td>
<td>海外・国際</td>
<td>2021</td>
<td><a href="#ref-26">ISO 4120: Sensory analysis — Methodology — Triangle test</a></td>
<td>識別試験規格／概要無料</td>
</tr>
<tr class="odd">
<td>27</td>
<td>海外・国際</td>
<td>2003</td>
<td><a href="#ref-27">ISO 4121: Sensory analysis — Guidelines for the use of quantitative response scales</a></td>
<td>尺度使用規格／概要無料</td>
</tr>
<tr class="even">
<td>28</td>
<td>海外・国際</td>
<td>2008／追補2016</td>
<td><a href="#ref-28">ISO 5492: Sensory analysis — Vocabulary</a></td>
<td>用語規格／概要無料</td>
</tr>
<tr class="odd">
<td>29</td>
<td>国内</td>
<td>2024改訂版の掲載を確認</td>
<td><a href="#ref-29">HACCPの考え方を取り入れた衛生管理のための手引書：小規模な一般飲食店</a></td>
<td>必読・衛生管理手引／本文無料</td>
</tr>
<tr class="even">
<td>30</td>
<td>国内</td>
<td>更新型／2026-09確認</td>
<td><a href="#ref-30">外食・中食での食物アレルギーについて</a></td>
<td>情報提供・運用資料／無料</td>
</tr>
</tbody>
</table>
<p><a id="ref-01"></a> ## 01. 日本摂食嚥下リハビリテーション学会嚥下調整食分類2021</p>
<p><strong>日本摂食嚥下リハビリテーション学会（2021／Q&amp;Aは2026-08追加まで公式一覧で確認）</strong>。日本摂食嚥下リハビリテーション学会雑誌 25(2):135–149 。</p>
<p><a href="https://www.jsdr.or.jp/doc/classification2021.html">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／必読・学会分類／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 食事ととろみの段階を共通の言葉で記述する国内の基盤資料。公式ページに本文、早見表、Q&amp;Aへの入口がある。</li>
<li><strong>モクテルへの応用：</strong> 国内での試作記録・施設間連携に使う。とろみは提供条件と測定条件を添えて記述する。</li>
<li><strong>限界・注意：</strong> IDDSI、UDF、特別用途食品の区分を単純に一対一対応させない。分類適合は個人の安全性の保証ではない。</li>
</ul>
<p><a id="ref-02"></a> ## 02. Complete IDDSI Framework: Detailed Definitions</p>
<p><strong>IDDSI（2019 v2.0（参照版。現行版との照合を要する））</strong>。International Dysphagia Diet Standardisation Initiative 。</p>
<p><a href="https://www.iddsi.org/images/Publications-Resources/DetailedDefnTestMethods/English/HR/V2DetailedDefnEnglish31july2019.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・国際分類／公式公開資料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 飲料と食品の性状を段階別に定義する国際的枠組み。学術論文と区別し、実務で使う定義文書として参照する。</li>
<li><strong>モクテルへの応用：</strong> 国際発表や英文の配合記録で、形態を共有する共通言語になる。</li>
<li><strong>限界・注意：</strong> 公式ページの本文取得に制限があり、公式試験資料・DRSの紹介も併用して確認した。利用時には言語版・版番号を確認する。</li>
</ul>
<p><a id="ref-03"></a> ## 03. Testing Methods for use with the IDDSI Framework</p>
<p><strong>IDDSI（2019-07-31）</strong>。IDDSI 。</p>
<p><a href="https://www.iddsi.org/images/Publications-Resources/DetailedDefnTestMethods/English/V2TestingMethodsEnglish31july2019.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・測定手順／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> フローテスト、フォーク・スプーンを用いる試験など、分類の確認に用いる方法を説明する。</li>
<li><strong>モクテルへの応用：</strong> 温度、調製後時間、用具を含む測定記録の雛形を作る際に読む。</li>
<li><strong>限界・注意：</strong> 任意のシリンジで同じ結果になるとは限らない。食事・飲料の各試験の適用範囲を本文で確認する。</li>
</ul>
<p><a id="ref-04"></a> ## 04. ユニバーサルデザインフード自主規格</p>
<p><strong>日本介護食品協議会（自主規格・版情報は公式案内で確認）</strong>。日本介護食品協議会 。</p>
<p><a href="https://www.udf.jp/about_udf/section_03.html">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／必読・業界自主規格／概要無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 介護食品のかたさ・粘度などによる区分と、UDFを支える自主規格の案内。</li>
<li><strong>モクテルへの応用：</strong> 市販原料の表示を理解し、調達時の候補を絞るために使う。</li>
<li><strong>限界・注意：</strong> 学会分類や行政の表示許可とは性格が異なる。加工・混合後の飲料に元の製品区分をそのまま付けない。</li>
</ul>
<p><a id="ref-05"></a> ## 05. 特別用途食品：えん下困難者用食品・とろみ調整用食品</p>
<p><strong>消費者庁（随時更新／2026-09確認）</strong>。消費者庁 。</p>
<p><a href="https://www.caa.go.jp/policies/policy/food_labeling/foods_for_special_dietary_uses">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／必読・行政制度／公開資料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 特別用途食品の制度、許可・基準・関連通知を確認する公式入口。</li>
<li><strong>モクテルへの応用：</strong> 医療向け製品の表示が何を意味するかを確認し、自作飲料の説明と区別する。</li>
<li><strong>限界・注意：</strong> 製品の表示許可と個別患者への適合は別。ここでは法令の詳細を再掲せず、使用時の現行通知へ遡る。</li>
</ul>
<p><a id="ref-06"></a> ## 06. スマイルケア食（新しい介護食品）</p>
<p><strong>農林水産省（随時更新／2026-09確認）</strong>。農林水産省 。</p>
<p><a href="https://www.maff.go.jp/j/shokusan/seizo/kaigo.html">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／行政の選択支援枠組み／公開資料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 栄養補給、噛むこと、飲み込むことへの配慮を区別して食品選択を支援する枠組み。</li>
<li><strong>モクテルへの応用：</strong> 家族向け説明や、提供対象を機能面と栄養面に分けて整理する際に使う。</li>
<li><strong>限界・注意：</strong> 色マークだけで嚥下機能を診断できない。各マークの使用条件は関連基準と併せて確認する。</li>
</ul>
<p><a id="ref-07"></a> ## 07. そしゃく配慮食品の日本農林規格（JAS）</p>
<p><strong>農林水産省（現行掲載版／2026-09確認）</strong>。農林水産省 JAS規格一覧 。</p>
<p><a href="https://www.maff.go.jp/j/jas/jas_standard/">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／国家規格／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> そしゃくしやすさに配慮した食品の品質・区分を規定する規格。公式一覧から該当本文へ進める。</li>
<li><strong>モクテルへの応用：</strong> ゲル状の副材料やフードとの組合せを考える際、咀嚼と嚥下を分けて理解する。</li>
<li><strong>限界・注意：</strong> そしゃく配慮の規格を、飲料の嚥下安全性の規格として使わない。改正・確認情報は公式一覧で追う。</li>
</ul>
<p><a id="ref-08"></a> ## 08. 摂食嚥下障害の評価2019</p>
<p><strong>日本摂食嚥下リハビリテーション学会（2019／訂正2021）</strong>。学会医療検討委員会資料 。</p>
<p><a href="https://www.jsdr.or.jp/wp-content/uploads/file/doc/assessment2019-announce.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／必読・評価資料／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 背景、身体機能、摂食嚥下の状態を整理する国内の評価資料。評価表と訂正情報も公式マニュアル一覧にある。</li>
<li><strong>モクテルへの応用：</strong> 試飲対象者の背景と観察事項を、嗜好の評価票とは別に記録するための基盤。</li>
<li><strong>限界・注意：</strong> 研究用アウトカムの妥当性を一括して保証する資料ではない。訂正情報も併読する。</li>
</ul>
<p><a id="ref-09"></a> ## 09. 嚥下造影の手順2026年度版</p>
<p><strong>日本摂食嚥下リハビリテーション学会（2026年度版）</strong>。学会医療検討委員会資料 。</p>
<p><a href="https://www.jsdr.or.jp/wp-content/uploads/file/doc/VF30-2-p158-182.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／更新資料・検査手順／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 嚥下造影検査の標準的な実施・評価を確認するための手順。学会の現行マニュアル一覧で2026年度版を確認した。</li>
<li><strong>モクテルへの応用：</strong> 研究計画でVFを用いる場合、検査条件と評価項目を再確認する。</li>
<li><strong>限界・注意：</strong> 造影剤を含む検査試料と実際のモクテルは同一物性とは限らず、その差を記録する。</li>
</ul>
<p><a id="ref-10"></a> ## 10. 嚥下内視鏡検査の手順2021改訂</p>
<p><strong>日本摂食嚥下リハビリテーション学会（2021改訂）</strong>。学会医療検討委員会資料 。</p>
<p><a href="https://www.jsdr.or.jp/wp-content/uploads/file/doc/endoscope-revision2021.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／検査手順／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 内視鏡検査の適応、説明・同意、機材、衛生管理、手技、評価などを扱う。</li>
<li><strong>モクテルへの応用：</strong> 臨床で実飲料を評価する際の検査手順と観察の限界を整理する。</li>
<li><strong>限界・注意：</strong> VEで確認できる局面と、直接観察できない局面を区別する。専門的な検査手順であり一般向け試飲手引ではない。</li>
</ul>
<p><a id="ref-11"></a> ## 11. 嚥下障害診療ガイドライン2024年版</p>
<p><strong>日本耳鼻咽喉科頭頸部外科学会（2024）</strong>。日本耳鼻咽喉科頭頸部外科学会／金原出版 。</p>
<p><a href="https://www.jibika.or.jp/modules/publish/index.php?content_id=7">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／必読・診療ガイドライン／公式案内、本文入手条件確認</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 嚥下障害診療の評価・対応を確認する国内ガイドライン。2024年版の刊行を学会公式ページで確認。</li>
<li><strong>モクテルへの応用：</strong> ST単独の食形態調整に閉じず、診断・医学的対応との関係を把握する。</li>
<li><strong>限界・注意：</strong> 本リストは公式案内に基づく紹介で、全推奨の全文検証ではない。適応するCQ・対象を本文で確認する。</li>
</ul>
<p><a id="ref-12"></a> ## 12. Adult Dysphagia — Practice Portal</p>
<p><strong>American Speech-Language-Hearing Association（更新型／2026-09確認）</strong>。ASHA 。</p>
<p><a href="https://www.asha.org/practice-portal/clinical-topics/adult-dysphagia/">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・臨床実践情報／公開</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 成人嚥下障害の評価、介入、食形態、患者の選好などへの入口と関連根拠を提供する。</li>
<li><strong>モクテルへの応用：</strong> 臨床と研究で考慮すべき項目の抜けを点検し、関連原著へ進む。</li>
<li><strong>限界・注意：</strong> 更新型の実践情報で、特定年の単独ガイドラインと同じ引用方法にしない。閲覧日を残す。</li>
</ul>
<p><a id="ref-13"></a> ## 13. Position paper on the use of thickened fluids in the management of people with swallowing difficulties</p>
<p><strong>Royal College of Speech and Language Therapists（2024公開版）</strong>。RCSLT 。</p>
<p><a href="https://www.rcslt.org/wp-content/uploads/2024/07/Thickened-fluids-position-paper.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・ポジションペーパー／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 増粘飲料の利益・負担・不確実性を整理し、臨床での検討を支える。</li>
<li><strong>モクテルへの応用：</strong> 水分摂取、本人の希望、継続しやすさを物性と並べて議論する重要資料。</li>
<li><strong>限界・注意：</strong> 系統レビューそのものではなく学会の立場文書。個々の推奨や根拠の質は本文で区別する。</li>
</ul>
<p><a id="ref-14"></a> ## 14. Eating and drinking with acknowledged risks: Multidisciplinary team guidance for the shared decision-making process (adults)</p>
<p><strong>Royal College of Speech and Language Therapists（2021）</strong>。RCSLT 。</p>
<p><a href="https://www.rcslt.org/wp-content/uploads/2021/09/Eating-and-drinking-with-acknowledged-risks-guidance.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・多職種意思決定指針／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 飲食に伴うリスクを認識した上での支援について、多職種での意思決定・記録・見直しを扱う。</li>
<li><strong>モクテルへの応用：</strong> 楽しみや社会的参加を目標に含む実践を、本人との合意形成に結びつける。</li>
<li><strong>限界・注意：</strong> 英国の制度・実務を前提とする部分がある。日本での責任や手続きをそのまま代替しない。</li>
</ul>
<p><a id="ref-15"></a> ## 15. ESPEN practical guideline: Clinical nutrition and hydration in geriatrics</p>
<p><strong>Volkert D ほか／ESPEN（2022）</strong>。Clinical Nutrition 41:958–989 。</p>
<p><a href="https://doi.org/10.1016/j.clnu.2022.01.024">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・実践ガイドライン／学会公開版あり</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 高齢者の栄養・水分管理について、実践的な推奨をまとめる。</li>
<li><strong>モクテルへの応用：</strong> モクテル提供の評価を、摂取量・栄養・脱水の観察と接続する。</li>
<li><strong>限界・注意：</strong> 楽しみの介入そのものの効果を示す資料ではない。対象と栄養上の目標を区別する。</li>
</ul>
<p><a id="ref-16"></a> ## 16. ESPEN guideline on nutrition and hydration in dementia – Update 2024</p>
<p><strong>Volkert D ほか／ESPEN（2024更新）</strong>。Clinical Nutrition 43:1599–1626 。</p>
<p><a href="https://doi.org/10.1016/j.clnu.2024.04.039">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／近年・診療ガイドライン／学会公開版あり</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 認知症のある人の栄養・水分支援について、2015年版を更新した指針。</li>
<li><strong>モクテルへの応用：</strong> 本人の食習慣や支援環境、疾患段階に応じた飲食の位置づけを検討する。</li>
<li><strong>限界・注意：</strong> すべての認知症の人に同じ介入が適するとは限らない。疾患段階と介入目的を確認する。</li>
</ul>
<p><a id="ref-17"></a> ## 17. European Stroke Organisation and European Society for Swallowing Disorders guideline for the diagnosis and treatment of post-stroke dysphagia</p>
<p><strong>Dziewas R ほか／ESO・ESSD（2021）</strong>。European Stroke Journal 6(3):LXXXIX–CXV 。</p>
<p><a href="https://doi.org/10.1177/23969873211039721">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／疾患別ガイドライン／公開版あり</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 脳卒中後の嚥下障害のスクリーニング、評価、治療をまとめた指針。</li>
<li><strong>モクテルへの応用：</strong> 脳卒中を対象とする研究で、標準的ケアに追加する実践の位置を明確にする。</li>
<li><strong>限界・注意：</strong> 脳卒中の推奨を他の神経疾患や頭頸部疾患へ自動的に拡張しない。</li>
</ul>
<p><a id="ref-18"></a> ## 18. Diagnosis and treatment of neurogenic dysphagia – S1 guideline of the German Society of Neurology</p>
<p><strong>Dziewas R ほか／German Society of Neurology（2021）</strong>。Neurological Research and Practice 3:23 。</p>
<p><a href="https://doi.org/10.1186/s42466-021-00122-3">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／疾患領域別指針／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 神経原性嚥下障害の診断・治療を、臨床評価から機器検査まで幅広く整理する。</li>
<li><strong>モクテルへの応用：</strong> 病態の違いを踏まえて飲料形態や評価方法を選ぶための俯瞰資料。</li>
<li><strong>限界・注意：</strong> S1という作成方法上の位置づけを踏まえ、すべての項目が高確実性の試験で裏付けられるとはみなさない。</li>
</ul>
<p><a id="ref-19"></a> ## 19. International Classification of Functioning, Disability and Health（ICF）</p>
<p><strong>World Health Organization（2001／オンライン情報更新型）</strong>。WHO 。</p>
<p><a href="https://www.who.int/classifications/international-classification-of-functioning-disability-and-health">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・国際分類／公式情報公開</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 心身機能、活動・参加、環境因子を関連づけて生活機能を記述する枠組み。</li>
<li><strong>モクテルへの応用：</strong> 飲む機能だけでなく、乾杯、交流、選択できる環境を研究の対象に位置づける。</li>
<li><strong>限界・注意：</strong> ICFの分類項目だけで、主観的な楽しみやウェルビーイングの尺度が完成するわけではない。</li>
</ul>
<p><a id="ref-20"></a> ## 20. Shared decision making</p>
<p><strong>National Institute for Health and Care Excellence（2021／NG197）</strong>。NICE 。</p>
<p><a href="https://www.nice.org.uk/guidance/ng197/chapter/recommendations">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／意思決定ガイドライン／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 本人と専門職が選択肢・利益・不利益・価値観を共有して決めるための推奨。</li>
<li><strong>モクテルへの応用：</strong> モクテルを飲みたいか、どの体験を重視するかを尋ねる面談設計に使う。</li>
<li><strong>限界・注意：</strong> 嚥下に特化したガイドラインではない。日本の実施体制と、意思表出に必要な支援を別途考える。</li>
</ul>
<p><a id="ref-21"></a> ## 21. ISO 6658: Sensory analysis — Methodology — General guidance</p>
<p><strong>ISO／日本語概要：FAMIC（2017）</strong>。ISO/TC 34/SC 12 。</p>
<p><a href="https://www.famic.go.jp/iso_codex_information/iso/sc12/_doc/iso_6658.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・官能評価規格／概要無料、規格本文別途</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 官能評価の方法論、共通手順、各種試験と結果の解釈を俯瞰する一般手引。</li>
<li><strong>モクテルへの応用：</strong> 識別・記述・嗜好のどの試験を行うのかを先に決めるために読む。</li>
<li><strong>限界・注意：</strong> 確認したのはFAMICの概要。正式な規格準拠をうたう場合は規格本文を確認する。</li>
</ul>
<p><a id="ref-22"></a> ## 22. ISO 8586: Sensory analysis — Selection and training of sensory assessors</p>
<p><strong>ISO／日本語概要：FAMIC（2023）</strong>。ISO/TC 34/SC 12 。</p>
<p><a href="https://www.famic.go.jp/iso_codex_information/iso/sc12/_doc/iso_8586.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／近年・評価者選抜と訓練／概要無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 訓練を受けた官能評価者・専門評価者の選抜基準と訓練を扱う。</li>
<li><strong>モクテルへの応用：</strong> 分析型パネルと、実際の利用者による嗜好評価を区別して設計する。</li>
<li><strong>限界・注意：</strong> 利用者全員に専門パネルと同じ能力を求める規格ではない。目的に合う参加者を選ぶ。</li>
</ul>
<p><a id="ref-23"></a> ## 23. ISO 8589: Sensory analysis — General guidance for the design of test rooms</p>
<p><strong>ISO／日本語概要：FAMIC（2007／追補2014、改訂作業中の表示を確認）</strong>。ISO/TC 34/SC 12 。</p>
<p><a href="https://www.famic.go.jp/iso_codex_information/iso/sc12/_doc/iso_8589.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／試験環境規格／概要無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 試験区域、調製区域など、官能評価を行う環境の設計を扱う。</li>
<li><strong>モクテルへの応用：</strong> 照明、におい、騒音などの外的条件を統制する際に参照する。</li>
<li><strong>限界・注意：</strong> 統制環境の結果だけでバーや在宅での体験は分からない。自然な場面の評価は別に計画する。</li>
</ul>
<p><a id="ref-24"></a> ## 24. ISO 13299: Sensory analysis — Methodology — General guidance for establishing a sensory profile</p>
<p><strong>ISO／日本語概要：FAMIC（2016）</strong>。ISO/TC 34/SC 12 。</p>
<p><a href="https://www.famic.go.jp/iso_codex_information/iso/sc12/_doc/iso_13299.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・官能プロファイル規格／概要無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 視覚・嗅覚・味覚・触覚などで知覚できる製品の特徴を記述するプロセスを扱う。</li>
<li><strong>モクテルへの応用：</strong> 甘味、酸味、香り、まとわりつき、後味などの評価語を組み立てる。</li>
<li><strong>限界・注意：</strong> 記述された強度と好ましさは別。すべての属性を高くすることが改善ではない。</li>
</ul>
<p><a id="ref-25"></a> ## 25. ISO 11136: Sensory analysis — Methodology — General guidance for conducting hedonic tests with consumers in a controlled area</p>
<p><strong>ISO／日本語概要：FAMIC（2014／追補2020）</strong>。ISO/TC 34/SC 12 。</p>
<p><a href="https://www.famic.go.jp/iso_codex_information/iso/sc12/_doc/iso_11136.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／必読・消費者嗜好試験規格／概要無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 統制された環境で消費者の好ましさを調べる試験の一般手引。</li>
<li><strong>モクテルへの応用：</strong> どの集団の好みを推定したいか、募集と提示条件をどう決めるかを検討する。</li>
<li><strong>限界・注意：</strong> 摂取量などの行動指標と、回答による嗜好評定は同じ測定ではない。対象者の回答負担にも配慮する。</li>
</ul>
<p><a id="ref-26"></a> ## 26. ISO 4120: Sensory analysis — Methodology — Triangle test</p>
<p><strong>ISO／日本語概要：FAMIC（2021）</strong>。ISO/TC 34/SC 12 。</p>
<p><a href="https://www.famic.go.jp/iso_codex_information/iso/sc12/_doc/iso_4120.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／識別試験規格／概要無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 2製品の間に知覚可能な差や類似性があるかを調べる3点試験法を扱う。</li>
<li><strong>モクテルへの応用：</strong> 増粘剤や抽出条件の変更が知覚できるかを調べる選択肢。</li>
<li><strong>限界・注意：</strong> 「差がある」は「好まれる」ではない。有意差がないことを無条件に同等性の証明としない。</li>
</ul>
<p><a id="ref-27"></a> ## 27. ISO 4121: Sensory analysis — Guidelines for the use of quantitative response scales</p>
<p><strong>ISO／日本語概要：FAMIC（2003）</strong>。ISO/TC 34/SC 12 。</p>
<p><a href="https://www.famic.go.jp/iso_codex_information/iso/sc12/_doc/iso_4121.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／尺度使用規格／概要無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 数値・言語・図などを使う定量的な反応尺度の使用を扱う。</li>
<li><strong>モクテルへの応用：</strong> 強度、好ましさ、飲みやすさで、質問文と尺度の両端を別々に決める。</li>
<li><strong>限界・注意：</strong> 尺度の数字だけを共通にしても測定概念は同じにならない。個人間比較の妥当性も検討する。</li>
</ul>
<p><a id="ref-28"></a> ## 28. ISO 5492: Sensory analysis — Vocabulary</p>
<p><strong>ISO／日本語概要：FAMIC（2008／追補2016）</strong>。ISO/TC 34/SC 12 。</p>
<p><a href="https://www.famic.go.jp/iso_codex_information/iso/sc12/_doc/iso_5492.pdf">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 海外・国際／用語規格／概要無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 官能評価の用語を定義するための規格。味、におい、風味などの整理の基盤となる。</li>
<li><strong>モクテルへの応用：</strong> 研究計画書と参加者向けの説明で、同じ語を違う意味で使うことを避ける。</li>
<li><strong>限界・注意：</strong> 専門用語をそのまま利用者に提示するのが最適とは限らない。分かりやすい表現との対応を作る。</li>
</ul>
<p><a id="ref-29"></a> ## 29. HACCPの考え方を取り入れた衛生管理のための手引書：小規模な一般飲食店</p>
<p><strong>日本食品衛生協会／掲載：厚生労働省（2024改訂版の掲載を確認）</strong>。厚生労働省 手引書一覧 。</p>
<p><a href="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000179028_00003.html">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／必読・衛生管理手引／本文無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 小規模な飲食店の衛生管理について、計画と実施記録を支える手引。</li>
<li><strong>モクテルへの応用：</strong> 抽出、冷却、保管、混合、提供までの工程を整理する。</li>
<li><strong>限界・注意：</strong> 味・物性の適合とは別の管理。試飲会・医療施設での実施条件は所属施設の手順と合わせる。</li>
</ul>
<p><a id="ref-30"></a> ## 30. 外食・中食での食物アレルギーについて</p>
<p><strong>消費者庁（更新型／2026-09確認）</strong>。消費者庁 。</p>
<p><a href="https://www.caa.go.jp/policies/policy/food_labeling/food_sanitation/allergy/efforts">原掲載先・公式資料</a></p>
<ul>
<li><strong>区分：</strong> 国内／情報提供・運用資料／無料</li>
<li><strong>選定理由：</strong> 発行責任が明確な学会・公的機関・専門組織の公式資料。</li>
<li><strong>内容：</strong> 外食・中食のアレルギー情報提供に関する教材・パンフレットへの入口。</li>
<li><strong>モクテルへの応用：</strong> 乳、卵、ナッツなどを含むモクテルの原材料説明と、器具の共用について整理する。</li>
<li><strong>限界・注意：</strong> 包装食品の表示と外食での情報提供を混同しない。個々の食材・製品と提供工程を確認する。</li>
</ul>
<hr>
<p>本資料は選定型の文献案内であり、網羅的システマティックレビューではない。飲料への応用は提案を含む。一般成人の物性・官能研究から、嚥下障害者の安全性・QOL改善を直接推定しない。</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "コピーしました");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "コピーしました");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/unotasuku\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>